version: '3'
services:
    bench:
      build:
        context: .
        dockerfile: BENCH
      container_name: bench
      tty: true
      stdin_open:  true
      volumes:
        - .:/app
        - /app/target
