version: '3'
services:
    # ganache:
    #   build:
    #     context: ganache
    #     dockerfile: Ganache
    #   container_name: ganache
    #   tty: true
    #   stdin_open: true
    #   ports:
    #     - 8545:8545
    deployer:
      build: geth
      container_name: deployer
      tty: true
      stdin_open: true
      volumes:
        - ./geth:/app
        - /app/node_modules
        - /app/build
    geth:
      build:
        context: geth
        dockerfile: Geth
      container_name: geth
      tty: true
      stdin_open: true
      ports:
        - 8545:8545
      command: --dev --dev.period 0 --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*" --http.api "eth,net,web3,personal,txpool,miner,debug" --verbosity 6 --datadir data
      volumes:
        - ./geth:/app
        - /app/data/geth
