[package]
name = "zkevm-circuits"
version = "0.1.0"
authors = ["therealyingtong <yingtong@z.cash>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.10"
halo2 = { git = "https://github.com/NoCtrlZ/halo2", rev = "677e594443c9f8fb80b41e7aacc79f5f81f7bd2d" }
bigint = "4"
num = "0.4"
sha3 = "0.7.2"
digest = "0.7.6"
array-init = "2.0.0"
paste = "1.0"
bus-mapping = { path = "../bus-mapping"}
pairing = { git = 'https://github.com/NoCtrlZ/pairing', package = "pairing_bn256" }

[dev-dependencies]
criterion = "0.3"
num = "0.4"
rand_xorshift = "0.3"
rand = "0.8"

[[bench]]
name = "binary_value"
harness = false

[[bench]]
name = "prover"
harness = false
