[package]
name = "geth-utils"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[build-dependencies]
gobuild = "0.1.0-alpha.1"

[dev-dependencies]
eth-types = { path = "../eth-types" }
serde = {version = "1.0.130", features = ["derive"] }
serde_json = "1.0.66"