name: CI checks

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
  push: # Run CI on the main branch after every merge. This is important to fill the GitHub Actions cache in a way that pull requests can see it
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Build and clippy
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: false
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
      - name: Build bus-mapping
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package bus-mapping --release
      - name: Build circuit-benchmarks
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package circuit-benchmarks --release
      - name: Build eth-types
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package eth-types --release
      - name: Build gadgets
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package gadgets --release
      - name: Build keccak256
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package keccak256 --release
      - name: Build mock
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package mock --release
      - name: Build prover
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package prover --release
      - name: Build zkevm-circuits
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package zkevm-circuits --release
      - name: Build all targets with all features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets --all-features
      # Run clippy always after build to re-use artifacts and shave time. See: https://www.reillywood.com/blog/rust-faster-ci/
      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          name: Clippy
          args: --all-features --all-targets -- -D warnings

  test:
    if: github.event.pull_request.draft == false
    name: Run all workspace tests
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
      - name: Test across the entire workspace
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --all-features --release --profile ci
      - name: Doctests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --all-features
