name: Integration Tests

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
  push:
    branches:
      - main

jobs:
  integration-tests:
    if: github.event.pull_request.draft == false

    name: Integration Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./integration-tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: false
      - name: Set PATH
        run: echo "${HOME}/bin" >> $GITHUB_PATH
      - name: Install Solc
        run: |
          mkdir -p "$HOME/bin"
          wget -q https://github.com/ethereum/solidity/releases/download/v0.8.10/solc-static-linux -O $HOME/bin/solc
          chmod u+x "$HOME/bin/solc"
          solc --version
      - name: Cache cargo index
        uses: actions/cache@v2
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-ubuntu-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo registry
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-ubuntu-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo target
        uses: actions/cache@v2
        with:
          path: target
          key: ${{ runner.os }}-ubuntu-cargo-target-${{ hashFiles('**/Cargo.lock') }}
      # Run an initial build in a sepparate step to split the build time from execution time
      - name: Build gendata bin
        run: cargo build --bin gen_blockchain_data
      - run: ./run.sh --steps "setup"
      - run: ./run.sh --steps "gendata"
      - run: ./run.sh --steps "tests" --tests "rpc"
      - run: ./run.sh --steps "tests" --tests "circuit_input_builder"
      - run: ./run.sh --steps "cleanup"
