name: Test feature flags

on:
  merge_group:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
  push:
    branches:
      - main

jobs:
  skip_check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          concurrent_skipping: 'same_content_newer'
          paths_ignore: '["**/README.md"]'

  test_features:
    needs: [skip_check]
    if: |
      github.event.pull_request.draft == false &&
      (github.event.action == 'ready_for_review' || needs.skip_check.outputs.should_skip != 'true')
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          override: false

      # Go cache for building geth-utils
      - name: Go cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ github.workflow }}-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ github.workflow }}-${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: 'zkevm-circuits: default'
        run: |
          GIT_ROOT=$(pwd)
          cd /tmp
          cargo new foobar
          cd foobar
          cp "${GIT_ROOT}/rust-toolchain" . || true
          cargo add --path "${GIT_ROOT}/zkevm-circuits"
          cargo build
          rm -rf foobar

      - name: 'zkevm-circuits: test-circuits'
        run: |
          GIT_ROOT=$(pwd)
          cd /tmp
          cargo new foobar
          cd foobar
          cp "${GIT_ROOT}/rust-toolchain" . || true
          cargo add --path "${GIT_ROOT}/zkevm-circuits" --features test-circuits
          cargo build
          rm -rf foobar
