[package]
name = "mpt-test"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers ={ version = "2.0.10", features = ["abigen", "rustls", "ws", "ethers-solc"] }
eth-types = { path = "../../eth-types" }
gadgets = { path = "../../gadgets" }
geth-utils = { path = "../../geth-utils" }
zkevm-circuits = { path = "../../zkevm-circuits", features=["test-circuits"]}
eyre = "0.6.11"
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2.git",  features=["circuit-params"], tag = "v0.3.0" }
serde_json = "1.0.111"
tokio = { version= "1.28.2", features = ["macros", "rt-multi-thread"]  }
glob = "0.3.1"
lazy_static = "1.4.0"
base64 = "0.21.7"
flate2 = "1.0.28"
hyper = { version="0.14.27",  features= ["full"]}
hyper-rustls = "0.24.1"
serde = "1.0.195"
hex = "0.4.3"

[features]
default = ["disable-keccak"]
disable-keccak = []
